version: 1

job:
  xpLevelUpRequirement:
    # XP requirement to level up
    base: 200.0

worldBlacklist:
  - blacklisted_world

# Possible values: SURVIVAL / ADVENTURE / CREATIVE / SPECTATOR
gameModeBlacklist:
  - CREATIVE
  - SPECTATOR

# Check this link for sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sounds:
  jobLevelUp:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 0.8
  questCompletion:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1
    pitch: 0.8
  objectiveCompletion:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1
    pitch: 0.8
