name: JobQuests
version: '1.0-SNAPSHOT'
main: me.exyin.jobQuests.JobQuests
api-version: '1.21'
authors: [ ExyiN ]
commands:
  jobquests:
    aliases: ["jq"]
    description: Main command
    permission: jobquests.use
permissions:
  jobquests.use:
    default: op